.\" ctrlproxy is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH ctrlproxy 1 "October 14, 2002"
.SH NAME
ctrlproxy \- an IRC proxy with multi-server and plugin support

.SH SYNOPSIS
.B ctrlproxy
[options]
.RI
.SH DESCRIPTION
\fBctrlproxy\fP is a modular IRC proxy. It connects 
to a number of IRC servers and then passes data it receives on 
to the modules that have been loaded into it. Current 
modules are client_simple (for proxy support) and 
log (for irssi-style log file generation).

.PP
.SH OPTIONS
\fBctrlproxy\fP recognizes the following command-line options
.TP
.B -D, --daemon
Go to the background after the program has been started (daemon mode).
.TP 
.B -r, --rc-file=RCFILE
Read configuration file from specified location 
.I RCFILE
instead of from 
.I .ctrlproxyrc
in the users home directory
.TP
.B -v, --version
Show copyright and version information
.TP
.B -?, --help
Show help message with short argument information
.TP
.B --usage
Display brief usage message

.SH "PLUGINS"
.PP
Current included plugins with ctrlproxy are:

.TP
\fBclient_simple\fP
Simple client framework. Multiple clients can connect to 
a specified port and then proxying to the specified server is done. 
Has password authentication support and multiple clients can 
connect.

.TP
\fBlog\fP
Log irc traffic to a specified file, using the same style 
as the irssi(1) IRC client does.

.SH "SEE ALSO"
.BR irssi (1), 
.BR ctrlproxyrc (5), 
.BR http://www.nl.linux.org/~jelmer/ctrlproxy/
.SH BUGS
Probably many, but none are known at the moment. Please send 
any you find to jelmer@nl.linux.org

.SH LICENSE
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
\fBWITHOUT ANY WARRANTY\fR; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.
.PP
You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple PLace, Suite 330, Boston, MA  02111-1307  USA

.SH AUTHOR
.PP
 Jelmer Vernooij <jelmer@nl.linux.org>
