.\" ctrlproxy is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH ctrlproxyrc 5 "October 14, 2002"
.SH NAME
ctrlproxyrc \- Configuration file for cgdb
.SH DESCRIPTION
.PP
A ctrlproxyrc configuration file consists of various sections, each section 
representing a server. Sections are started by 
putting a section name between brackets ([ and ]) on a new line. Sections 
can have any name as long as it doesn't have a ']' in it. Section names 
don't have any special meaning.
.PP
Each section has various variables, all following the section declaration, 
and consisting of a name and a value, seperated by a space. If a variable 
is not specified in a section, ctrlproxy tries to use the value of 
the 'global' variable. (Global variables are variables outside of 
any section).
.PP
Lines starting with a # are comments and therefore ignored by the parser.

.SH "BASIC VARIABLES"
.TP
\fBhost\fP
Specify the name of the server to connect to. Required.

.TP
\fBport\fP
Specify the port of the server to connect to. Defaults to 6667.

.TP
\fBnick\fP
Nick to use on the network. Defaults to unix username.

.TP
\fBautojoin\fP
Comma-seperated list of channels to join when connected.

.TP
\fBpass\fP
Password used to log in to server.

.TP
\fBmodules\fP
Modules to load

.SH "MODULES"
.PP
This section contains a list of variables supported by the modules included with 
ctrlproxy:

.TP
\fBclientpass\fP (client_simple)
Password clients have to use to connect to the proxy

.TP
\fBclientport\fP (client_simple)
Port to listen on for new client connections.

.TP
\fBlogfile\fP (log)
Filename to log irc traffic to. First %s is replaced by name of 
IRC server, second is replaced by channel or nick name.

.SH "SEE ALSO"
.BR ctrlproxy (1), 
.BR smb.conf (5),
.BR ctrlproxyrc.example,
.BR http://www.nl.linux.org/~jelmer/ctrlproxy/

.SH LICENSE
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
\fBWITHOUT ANY WARRANTY\fR; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.
.PP
You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple PLace, Suite 330, Boston, MA  02111-1307  USA

.SH AUTHOR
.PP
 Jelmer Vernooij <jelmer@nl.linux.org>
